# Generated by Django 5.0.6 on 2025-12-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_description', models.TextField(verbose_name='Опис помилки')),
                ('date_received', models.DateField(verbose_name='Дата надходження')),
                ('error_level', models.CharField(choices=[('critical', 'Критична'), ('important', 'Важлива'), ('minor', 'Незначна')], max_length=10, verbose_name='Рівень помилки')),
                ('category', models.CharField(choices=[('interface', 'Інтерфейс'), ('data', 'Дані'), ('algorithm', 'Розрахунковий алгоритм'), ('other', 'Інше'), ('unknown category', 'Невідома категорія')], max_length=50, verbose_name='Категорія')),
                ('source', models.CharField(choices=[('user', 'Користувач'), ('tester', 'Тестувальник')], max_length=20, verbose_name='Джерело')),
            ],
            options={
                'verbose_name': 'Помилка',
                'verbose_name_plural': 'Помилки',
                'db_table': 'errors',
            },
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Програміст',
                'verbose_name_plural': 'Програмісти',
                'db_table': 'programmers',
            },
        ),
        migrations.CreateModel(
            name='BugFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата початку виправлення')),
                ('duration_days', models.IntegerField(choices=[(1, '1 день'), (2, '2 дні'), (3, '3 дні')], verbose_name='Термін виправлення (днів)')),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість 1 дня роботи')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug_app.error', verbose_name='Помилка')),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bug_app.programmer', verbose_name='Програміст')),
            ],
            options={
                'verbose_name': 'Виправлення помилки',
                'verbose_name_plural': 'Виправлення помилок',
                'db_table': 'bug_fixes',
            },
        ),
    ]
